### ISSUE TITLE
ASRock Z390 pg itx USB驱动

### ISSUE THREAD

**Issue by Jason-Quan** [seanzhang98/seanzhang98#1]
您好，使用您的EFI文件装的Big Sur 11.1，除了USB有些问题，其他都正常。
主板后边的USB只有部分能使用，还有前置的USB也不能使用，但在win10下都可以。
请问有什么方法解决吗？非常感谢。
<img width="1466" alt="Screen Shot 2021-02-08 at 13 09 50" src="https://user-images.githubusercontent.com/78159285/107178343-f0626a00-6a0e-11eb-9e3c-ffd385adbf6a.png">

**Comment by seanzhang98** [comment]
@Jason-Quan 自行定制USB
